#pragma once
#include "framework.h"

map<string, map<string, map<string, wstring>>> strings = {
	{"ENG", {
		{"NPCNames", {
			{"???",L"???"},
			{"Angela Fleuret", L"Angela Fleuret"},
			{"Tianshun Song", L"Tianshun Song"},
			{"Olyver Sumner", L"Olyver Sumner"},
			{"Hernando Pizarro", L"Hernando Pizarro"},
			{"Gihat al-Din Jaqmaq", L"Gihat al-Din Jaqmaq"},
			{"Father Michelet", L"Father Michelet"},
			{"Isobella de Vaines", L"Isobella de Vaines"},
			{"Father Charlot", L"Father Charlot"},
			{"Colette Verderonne", L"Colette Verderonne"},
			{"GuardM1", L"Adam Croix"},
			{"GuardF1", L"Nicole de Frise"},
			{"PeasantF1", L"Rohesia Elwood"},
}},
		{"Skill Tree Names", {
			{"Cleromancy", L"Cleromancy"},
			{"Hagiomancy", L"Hagiomancy"},
			{"Necromancy", L"Necromancy"},
			{"Sangromancy", L"Sangromancy"},
			{"Meteomancy", L"Meteomancy"},
			{"Electromancy", L"Electromancy"},
			{"1H Weapon Mastery", L"1H Wep Mastery"},
			{"Wayfaring", L"Wayfaring"},
			{"Umbromancy", L"Umbromancy"},
			{"Dual Weapon Mastery", L"D Wep Mastery"},
			{"Wayfaring", L"Wayfaring"},
			{"DEFAULT", L""},
}},
		{"Skill Names", {
			{"DEFAULT_ATTACK", L"Attack"},
			{"DEFAULT_WAIT", L"Wait"},
			{"Heal Wounds", L"Heal Wounds"},
			{"Heavenstrike", L"Heavenstrike"},
			{"Light of Day", L"Light of Day"},
			{"Exile", L"Exile"},
			{"Strength of Reason", L"Strength of Reason"},
			{"Life Drain", L"Life Drain"},
			{"Animate Skeleton Warrior", L"Animate Skeleton Warrior"},
			{"Rainstorm", L"Rainstorm"},
			{"Plasma Pulse", L"Plasma Pulse"},
			{"Doublestrike", L"Doublestrike"},
			{"Shadow Spike", L"Shadow Spike"},
			{ "Fine Strike", L"Fine Strike" },
			{ "Gentleman's Riposte", L"Gentleman's Riposte" }
}},
		{"Skill Descriptions", {
			{"DEFAULT_ATTACK", L"Perform a physical attack against target foe that deals②$POWER1$ damage."},
			{"DEFAULT_WAIT", L"Skip this current turn." },
			{"Heal Wounds", L"Heal target ally for②$POWER1$ life." },
			{"Heavenstrike", L"Deal②$POWER1$ holy damage to target foe. If the damage is fatal, all allies are healed for②$POWER2$ life and Heavenstrike takes an additional 4 rounds to recharge." },
			{"Light of Day", L"Deal②$POWER1$ holy damage to all undead or demonic foes." },
			{"Strength of Reason", L"Enchant target ally with Strength of Reason for②$POWER1$ rounds. Their physical attacks deal an extra②$POWER2$ holy damage." },
			{"Exile", L"Destroy target summoned creature. Exile takes an additional②$POWER1$ rounds to recharge." },
			{"Life Drain", L"Curse target foe for②$POWER1$ rounds. Every round, you steal②$POWER2$ life from target foe."},
			{"Animate Skeleton Warrior", L"Animate a Skeleton Warrior that has②$POWER1$ life and a bonus②$POWER2$ Strength."},
			{"Rainstorm", L"Start a rainstorm which lasts for②$POWER1$ rounds and applies Wetness to everyone for②$POWER1$ rounds. Being wet reduces armour against cold and electric damage by 25%, but increases that of fire damage by 25%."},
			{"Plasma Pulse", L"Target foe is struck for②$POWER1$ electric damage and is left concussed for②$POWER2$ rounds, making their spells 50% more likely to fail."},
			{"Doublestrike", L"Strike target foe twice. Each strike deals an extra②$POWER1$ damage."},
			{"Shadow Spike", L"Target foe and all adjacent foes are interrupted and blinded for 1 round. Shadow Spike takes an additional②$POWER1$ rounds to recharge."},
			{"Fine Strike", L"Strike target foe. This attack is②$POWER1$% more likely to be a critical hit."},
			{"Gentleman's Riposte", L"For②$POWER1$ rounds, the next time an ally would be struck by a foe's physical attack, the attack is blocked and a physical attack is attempted against that foe."},
}},
		{"Other Stat Names", {
			{"LIFEREGEN", L"Life⑳Regeneration"},
			{"ENERGYREGEN", L"Energy⑳Regeneration"},
}},
		{"Type Names",{
			{"HOLY", { L"holy"}},
			{"FIRE", { L"fire"}},
			{"ELECTRIC", { L"electric"}},
			{"ELEMENTAL", { L"elemental"}},
			{"WEATHER", { L"weather"}},
			{"UNHOLY", { L"unholy"}},
			{"BLOOD", { L"blood"}},
			{"SHADOW", { L"shadow"}},
			{"PHYSICAL", { L"physical"}},
			{"WAYFARING", { L"Wayfaring"}},
}},
		{"Skill Actions", {
			{"Wait", L"$WHO$ is waiting..."},
			{"Default_Started", L"$WHO$ is using a skill..."},
			{"Attack_Started", L"$WHO$ is preparing an attack..."},
			{"Spell_Started", L"$WHO$ is casting a spell..."},
			{"Default_Finished", L"$WHO$ uses $SKILLNAME$!"},
			{"Attack_Finished", L"$WHO$ uses $SKILLNAME$!"},
			{"Spell_Finished", L"$WHO$ casts $SKILLNAME$"},
}},
		{"Item Type Names", {
			{"Armour", L"Armour"},
			{"Weapon", L"Weapon"},
			{"Accessory", L"Accessory"},
}},
		{"Item Names", {
					{"Withered Secespita", L"Withered Secespita"},
					{"Vatican Vestiments", L"Vatican Vestiments"},
					{"Cross of St Jeanne-Marie", L"Cross of St Jeanne-Marie"},
					{"Suero's Blade", L"Suero's Blade"},
					{"Matteo Carreri's Locket", L"Matteo Carreri's Locket"},
					{"Martin's Cloak", L"Martín Alhaja's Cloak" },
					{"Blades of House JaqMaq", L"Blades of House JaqMaq"},
					{"Theoricae Novae Planetarum", L"Theoricae Novae Planetarum"},
					{"Lunyu Page Fragment", L"Lunyu Page Fragment"},
					{"Tibetan Tie Bian", L"Tibetan Tie Bian"},
					{"Mask of House JaqMaq", L"Mask of House JaqMaq"},
					{"Alhambran Tunic", L"Alhambran Tunic"},
					{"Joan of Arc's Necklace", L"Joan of Arc's Necklace"},
					{"The Eyes of St Lucy", L"The Eyes of St Lucy"},
					{"Insulating Gloves", L"Insulating Gloves"},
					{"Ming Theatre Costume", L"Ming Theatre Costume"},
					{"Roger Bacon's Quill", L"Roger Bacon's Quill"},
					{"al-Hajar al-Aswad", L"al-Hajar al-Aswad"},
		}},
		{"Item Descriptions", {
					{"Withered Secespita", L"A secespita is an iron-bladed knife ranging from 8 to 10 inches in length with a rounded ivory handle. It usage dates as far back as the 2nd Century AD,  where ritualists of the pre-Christian Roman Empire, known as Flamens and Flaminicae, would use the blade to kill animals as part of a sacrifice. Such an offering would have been made either to a certain God or Goddess, or as a plea for Rome to be victorious in a particular war, or saved from a particular threat. To complete the ritual, the Secespita would then be used to disembowel the victim.\n\nThis Secespita in particular seems to have been forged to have a thinner blade than usual, giving it a 'withered' look. In spite of this characteristic, as well as being well over a thousand years old, it looks to be uncannily well-preserved, as if an Ancient Roman had walked up to you in the street and dropped it calmly into your open palm before walking away."},
					{"Vatican Vestiments", L"This sensible garment is hand woven for senior members of the clergy. A priest's robes are known as liturgical vestments and can comprise of many lengthy garments from chasubles to copes, mitres to mantles.\n\nThese robes in particular, however, are drastically more simple and are more appropriate to travelling and combat over evangelising."},
					{"Cross of St Jeanne-Marie", L"Jeanne-Marie de Maille was an Anchoress who lived and died in the 14th and 15th centuries respectively. An Anchoress is a woman who, either symbolically or literally, consents to being imprisoned in a holy chamber for the purpose of living a sinless, isolated life, in endless service to God. They are at times considered 'already dead', and instead of living people, are treated as a kind of 'living saint'.\n\nThis cross in particular was forged by Jeanne-Marie during her period of hermeticism and therefore remains infused with her desire to serve God."},
					{"Suero's Blade", L"Suero de Quiñones, the heroic knight of León, is famous for hosting the Paso Honroso (Passage of Honour), a jousting tournament for Spain's up-and-coming riders. Suero and his company enjoy the legend of having challenged thousands of knights in a total of 166 separate battles. Such heroism, however, is dimmed by the selfishness and cruelty he expressed as recently as 1449. Heavily indebted to a Jewish lender and looking for a way out, Suero stirred up hatred of the Jewish population of León by claiming they were collectively responsible for the death of Jesus. A violent uprising against the Jews took place in the town with hundreds of Jews murdered in the street, Suero's lender among them. Suero was said to have lost this sword in the carnage.\n\nYou can feel the pain this sword endures as a symbol of hope stained with the blood of wickedness. It does not wish to be returned to its original owner."},
					{"Matteo Carreri's Locket", L"This odd item is a flower that has been dried, pressed, and preseved inside a locket of silver with a simple chain. It is said to have been gifted to a little girl rescued from Turkish pirates who were trying to sell her and her mother into slavery. The story of the legendary friar Matteo Carreri is that he, too, was captured by the same pirates, who agreed to free him after Matteo produced a strong sermon of Christian belief. However, once he realised that a mother and child were still held captive, he offered to give up his newfound freedom and take the girl's place while she be freed. Stunned by his altruism, the pirates freed everyone. As a token of gratitude, the girl gave Matteo a flower, which he had preserved into the locket.\n\nYou are unsure how the locket left Matteo's custody, but assume the friar gave up such fineries to pursue a more pious purpose."},
					{"Martin's Cloak", L"This cloak once belonged to Martín Alhaja, a simple farmer and shepherd who helped guide the Castilian King Alfonso VIII to victory in the Battle of Las Navas de Tolosa in 1212. He placed the skull of a cow on the path that would lead to a field behind the Moors, allowing Alfonso's army to perform a surprise attack from behind. Alhaja was honoured for life for the part he played in the king's victory, and this fine silk cloak was a royal gift. It seems likely that it was never worn, being too fine and fancy for the man's tastes. Instead it was excellently preserved as a hand-me-down.\n\nThe cloak is fine and soothing to the touch and you feel more relaxed simply by wearing it."},
					{ "Blades of House JaqMaq", L"The design of these swords was commissioned by the Sultan of Egypt, Sayf al-Din Jaqmaq, in 1448, as a birthday gift to his daughter Gihat. The craftsman in question was a brillian Indian blacksmith who took into account the needs of its user very carefully when bringing the design to life. It is quite similar to a traditional Indian Talwar from the 14th century. However, he made the blades shorter and wider, and had them weighted in such a way to favour moving silently and without hindrance over brute force.\n\nBy holding one of the blades, you can feel the absolute joy and gratitude of a young woman seeking recognition as an assassin." },
					{"Theoricae Novae Planetarum", L"This tatty, hand-written tome is a collection of various manuscripts, drafts, and scribblings by Georg von Peuerbach, a young and ambitious lecturer at the University of Vienna. He specialises in the pioneering edge of astronomy and aspires to bring enlightenment to the world. While much of the scribblings are incomprehensible to a mere mortal, they generally dictate the concept that the Earth revolves around the Sun.\n\nYou feel smarter simply by holding the book." },
					{"Lunyu Page Fragment", L"Originally written in around 210 BC, the Lunyu is a compilation of anectdotal wisdom written by the great philosopher Confucius. While deeply respected, its status remained dormant for a thousand years until it was officially canonized during the Song Dynasty. This page in particular is a reproduction from around 1250, and while it does seem well preserved considering its 200 years of age, you can't help but notice that it was clearly ripped out of a book. This page in particular details the Chinese concept of xiao (孝) - filial piety and devotion to one's parents.\n\nSomething doesn't feel right about this fragment, almost as if the one who ripped it out of the book was cursing its original pledge." },
					{ "Tibetan Tie Bian", L"The Tie Bian (鐵鞭), is a small ornate iron rod designed to parry and break weapons, and this one was once gifted to a Tibetan Priest named Butön Rinchen Drup by his Mongol Lord. At the time, Tibet was subject to Mongol rule, but managed to enjoy a period of relative stability and prosperity, with the Tibetan priests acting as spiritual and political leaders while their masters, the Mongols, provided the substantial military power needed to keep the peace.\n\nThis particular Tie Bian is smaller than usual and seems to serve a more decorative purpose than most Tie Bians." },
					{ "Mask of House JaqMaq", L"This simple silk mask is used to hide an assassin's identity from those who would identify him or her as a killer. Discretion is essential in matters of death, and this garment is no exception. It was delicately sewn by a servant of the House of JaqMaq, the current ruling dynasty of Egypt.\n\nThe mask allows the user to act without hesitation." },
					{ "Alhambran Tunic", L"The exquisite craftsmanship of this perfectly-fitting silk tunic and harem pants reveal the origin of these clothes - Granada. The last stronghold in Spain still controlled by the Moors, these clothes were privately commissioned by Gihat al-Din JaqMaq as a practical alternative to the puffy, billowing cloaks and veils that would impede her ability to be effective in combat.\n\nDespite the bloodshed, these garments are as pristine as they were the day she had her fitting for them." },
					{ "Joan of Arc's Necklace", L"This plain gold necklace adorned with the Christian Cross was worn by Joan of Arc on the day she was burned at the stake. While Joan herself accepted her cruel fate as a part of God's plan, hundreds of thousands of witches throughout the Western world were spiritually wounded by the outrageous and terrible injustice. In that singular moment of united sorrow, their combined grief birthed a spiritual entity which cursed the necklace, permanently sealing away a single flame from the pyre that continues to burn 19 years after La Pucelle's death.\n\nYou can see waves of powerful heat rising from the necklace and you fear wearing it would invite disaster upon you." },
					{ "The Eyes of St Lucy", L"This pair of perfectly-preserved eyeballs have been delicately tied together by their nerve endings as if they were ribbons rather than the flesh of a revered saint. Nevertheless, these were once the eyes of St Lucy. She lived and died in the 3rd and 4th centuries respectively, at a time when the growing sprouts of Christianity were starting to cast Roman Paganism into the shadow. Despite being a wealthy woman betrothed to a Roman, Lucy insisted on sharing her wealth with others in accordance with her Christian faith. Outraged by her heresy, the Governor of Syracuse ordered for her to be taken to a brothel and raped. By some miracle, all the Governor's horses and men couldn't move Lucy even an inch. It is said that when one of the men decided to stab Lucy with a sword, her eyes shone brightly in blinding rays of judgement that disintegrated everyone in sight. The only thing that remained were the eyes, now dormant." },
					{ "Insulating Gloves", L"In the 4th Century BC, almost a thousand years before the current day, the great Greek philosopher Aristotle theorised about the origin of lightning. He described how water in the atmosphere, upon moving higher in the sky, becomes colder and denser as it collects back into liquid form. This disparity of temperatures between colder, higher clouds and warmer, closer clouds causes a burst of movement in which the hot air escapes from the cold and starts to burn in a thin, brilliant line known as lightning. Unsatisfied by the alleged universality of this theory, Olyver Sumner had these gloves made to be thickly insulated to protect him from electricity so he can study it safely." },
					{ "Ming Theatre Costume", L"The history of modern theatre in China may trace its roots to as far back as the 12th Century. The Tang Buddhist tradition of bianwen (變文) mixed speech, song, and dance and was utilised by Buddhist monks to communicate their teachings to the common illiterate masses. Such an entertaining art form spread among the populace, not as a religious tool, but as a form of entertainment. This particular costume would typically have been worn by a girl starting her career in a travelling opera troop performing shows for anyone with coin to spend.\n\nUnlike most actresses, however, this costume is stained with the blood and sinew associated with corpses." },
					{"Roger Bacon's Quill", L"Roger Bacon was a revered English scholar, friar and philosopher whose studies and interests were rich and widespread, ranging from gunpowder to astronomy to theology to grammar. His open-mindedness in accepting wisdom and knowledge from all corners of the earth, a drastic departure from many of the ignorant zealots of his era, made him an exceptional thinker of his time. Unbeknownst to many, even now, is that Roger Bacon was also a highly proficient wizard who specialised in the creation of automata - that is to say, self-thinking golems such as the Brazen Head, an animated creature capable of answering simple yes or no questions.\n\nIt is said that this quill was used to jot down some of the friar's most intelligent musings."},
					{"al-Hajar al-Aswad", L"According to Islamic mythology, God commanded that Adam build the Kaaba to be the earthly counterpart of the house of Heaven. After its destruction during the biblical flood, Ibrahim and Ismail were tasked with its reconstruction. As Ismail was out searching for stones to use, he came face to face with the Arch-Angel Jibrail, who gave him a dense, black rock. Arabic literature strongly indicates that this stone fell directly from heaven where it was once white and pure, but was stained forever black by the sins of humanity.\n\nYou feel a strong but conflicting sense of power from the stone, as if it represented both Allah's magnificence and humanity's wickedness."},
		}},
		{"Item Effect Strings", {
				{"XBOOST", L"Increases the power of⑳$REPLACE1$ skills by⑳$REPLACE2$"},
				{"ATTUPP", L"Increases⑳$REPLACE1$ by⑳$REPLACE2$"},
				{"ARMOUR", L"Increases resistance against⑳$REPLACE1$ attacks by⑳$REPLACE2$"},
		}},
		{"Unique Item Strings", {
			{"TOMEOF", L"Tome of "},
			{"TEACHES", L"Teaches the skill $REPLACE$. Can only be used once."},
			{"SELFIMMOLATE",L"You are set on fire at the start of every round."},
}},
		{"Attribute Names", {
			{"STRENGTH", L"Strength"},
			{"INTELLIGENCE", L"Intelligence"},
			{"VITALITY", L"Vitality"},
			{"PIETY", L"Piety"},
			{"AGILITY", L"Agility"},
			{"LUCK", L"Luck"},
}},
		{"Stat Names", {
			{"LIFE", L"Life"},
			{"ENERGY", L"Energy"},
			{"ENERGYREGEN", L"Energy Regen"},
			{"SPEED", L"Speed"},
}},
		{"GUI", {
			{"RETURN", L"Return"},
			{"MERCHANTTHANKSBuy", L"Thank you for your custom! Let me know if any of my other items may interest you!"},
			{"MERCHANTTHANKSBuyback", L"Thank you for your custom!"},
			{"MERCHANTTHANKSSell", L"This is a great item! Thank you for selling it to me at such a fair price!"},
			{"CAN'TAFFORD", L"You do not have enough money to purchase this item."},
			{"NOSPACE", L"You can't buy any more of this item because you already have 99 copies of it. Seriously, why do you need so many?"},
			{"SFXVolume", L"SFX Volume"},
			{"AmbienceVolume", L"Ambience Volume"},
			{"MusicVolume", L"Music Volume"},
			{"MANAGEPARTYBUTTON", L"Manage Party"},
			{"RESUMEEXPLOREBUTTON", L"Resume"},
			{"AUDIOOPTIONS", L"Audio Settings"},
			{"QUITBUTTON", L"Quit"},
			{"CANCELBUTTON", L"Cancel"},
			{"FROMAUDIOTOPAUSEBUTTON", L"Return"},
			{"QUITTEXT", L"Are you sure you want to quit? \n\n (Ritual of the Rose automatically saves your progress for when you return)"},
			{"FROMPARTYTOPAUSE", L"Return"},
			{"PARTYMANAGEHELP", L"Help"},
			{"XPOINTSLEFT", L" points left to spend."},
			{"1POINTLEFT", L" point left to spend."},
			{"PHYSICALPOWER", L"Physical Power:\t②"},
			{"MAGICALPOWER", L"Magical Power:\t②"},
			{"NOTEXT", L""},
			{"equipmentToggleText", L"Show / Hide Equipment Effects"},
			{"FROMPARTYTOREFORM", L"Reform Party"},
			{"PARTYLABEL", L"Party"},
			{"RESERVELABEL", L"Reserves"},
			{"FROMPARTYMANAGEMENTTOSKILLMANAGE", L"Change Skills"},
			{"FROMPARTYMANAGEMENTTOEQUIPMENT", L"Change Equipment"},
			{"SELECTCHARACTER", L"Select Character:"},
			{"CANCELSKILLTREECHOICE", L"Cancel"},
			{"SKILLTREESELECTIONEMPTY" , L"Skill Tree ↓"},
			{"SKILLTREESELECTION1", L"Select Skill Tree (Current: $REPLACE$)"},
			{"SKILLTREESELECTION2", L"Select Skill Tree (Current: $REPLACE$)"},
			{"EQUIPMENTSELECT", L"Select Equipment Type →"},
			{"Weapon", L"Weapons ↓"},
			{"Armour", L"Armour ↓"},
			{"Accessory", L"Accessories ↓"},
			{"MERCHANTTOEXPLORE", L"Leave Shop"},
			{"MERCHANTBUY", L"Buy"},
			{"MERCHANTSELL", L"Sell"},
			{"MERCHANTBUYBACK", L"Buyback"},
			{"Yes", L"Yes"},
			{"No", L"No"},
			{"Buy", L"buy"},
			{"Sell", L"sell"},
			{"Buyback", L"buyback"},
			{"TradeConfirm", L"Are you sure you want to $MODE$ the $ITEM$ for $PRICE$ livres?"},
			{"TradeConfirmPlus_Buy", L"You already have $AMOUNT$ of these in your inventory."},
			{"TradeConfirmPlus_Buyback", L"You already have $AMOUNT$ of these in your inventory."},
			{"TradeConfirmPlus_Sell", L"You currently have $AMOUNT$ of these in your inventory."},
			{"You found other", L"You found an item:"},
			{"You found weapon", L"You found a weapon:"},
			{"You found armour", L"You found some armour:"},
			{"You found accessory", L"You found an accessory:"},
			{"You found tome", L"You found a tome:"},
			{"TUTTEXTBOX", L"Will you fight the Mad Knight?\n\n(Play the Combat Tutorial?)"},
			{"TUTNO", L"Skip Tutorial"},
			{"TUTYES", L"Play Combat Tutorial"},
}},
		{"Map Pop Up Text", {
			{"Dead Horse", L"Press the Spacebar to interact with objects of interest"},
			{"Corpse of a female villager", L"Corpse of a female villager"},
			{"Corpse of a male villager", L"Corpse of a male villager"},
			{"Enter House", L"Enter House"},
			{"Leave House", L"Leave House"},
			{"A Roaring Fireplace", L"A Roaring Fireplace"},
			{"Talk to OldBookMan", L"Talk to Remy de Rouen"},
			{"Go Upstairs", L"Go Upstairs"},
			{"Go Back Downstairs", L"Go Back Downstairs"},
			{"Open Chest", L"Open Chest"},
			{"Enter Bénouville", L"Enter Bénouville"},
			{"Leave Bénouville", L"Leave Bénouville"},
			{"Enter Smithy", L"Enter Smithy"},
			{"Enter Tavern", L"Enter Tavern"},
			{"Leave Smithy", L"Leave Smithy"},
			{"Leave Tavern", L"Leave Tavern"},
			{"Enter Iso", L"Visit Isobella de Vaines"},
			{"Talk to the Cat", L"Talk to the Cat"},
			{"Talk to the Cat 2", L"Talk to Breone"},
			{"Talk to the Dog", L"Talk to the Dog"},
			{"Pray at Grave", L"Pray at this grave"},
			{"Talk to Gravedigger", L"Talk to Father Charlot"},
			{"Talk to MerchantNPC1", L"Talk to François Burgandy"},
			{"Talk to MerchantNPC2", L"Talk to Hannequin de Souffregard"},
			{"Talk to MerchantNPC3", L"Talk to Rosceline Verderonne"},
			{"Talk to OldWoman1", L"Talk to Colette Verderonne"},
			{"Talk to TownGuards1", L"Talk to Town Guards"},
			{"Talk to Beggar", L"Talk to Beggar"},
			{"Talk to Blacksmith", L"Talk to Blacksmith"},
			{"Talk to Isobella", L"Talk to Isobella de Vaines"},
			{"Talk to Father Michelet", L"Talk to Father Michelet"},
			{"View Isobella", L"View Isobella's Wares"},
		}},
		{ "Default Merchant Dialogue", {
			{"Buy" , L"Greetings, traveller, and welcome to my store! I have some items for sale that might interest you! If you have any questions don't hesitate to ask, I'm here to help."},
			{"Sell", L"If you have any items you'd like to part with, I'd be more than happy to take a look. I'll offer you a fair rate!"},
			{"Buy Back", L"As a standing member of the Traders' Association, I take part in the Merchant Buyback Scheme. If you've sold us an item and you've changed your mind, you can buy it back for exactly the same price we originally paid."}
		} },
		{ "Terms Per Character", {
		{"Angela Fleuret_PoliteTitle", L"Madame Fleuret"},
		{"Tianshun Song_PoliteTitle", L"Miss Song"},
		{"Olyver Sumner_PoliteTitle", L"Mr Sumner"},
		{"Hernando Pizarro_PoliteTitle", L"Señor Pizarro"},
		{"Gihat al-Din Jaqmaq_PoliteTitle", L"Miss Jaqmaq"},
		{"Angela Fleuret_GenderUpper", L"HER"},
		{"Tianshun Song_GenderUpper", L"HER"},
		{"Olyver Sumner_GenderUpper", L"HIM"},
		{"Hernando Pizarro_GenderUpper", L"HIM"},
		{"Gihat al-Din Jaqmaq_GenderUpper", L"HER"},
		{"Angela Fleuret_Gender", L"her"},
		{"Tianshun Song_Gender", L"her"},
		{"Olyver Sumner_Gender", L"him"},
		{"Hernando Pizarro_Gender", L"him"},
		{"Gihat al-Din Jaqmaq_Gender", L"her"},
		{"Angela Fleuret_Polite", L"good woman"},
		{"Tianshun Song_Polite", L"young lady"},
		{"Olyver Sumner_Polite", L"good sir"},
		{"Hernando Pizarro_Polite", L"good sir"},
		{"Gihat al-Din Jaqmaq_Polite", L"good woman"},
		{"Angela Fleuret_Kind", L"old lady"},
		{"Tianshun Song_Kind", L"little girl"},
		{"Olyver Sumner_Kind", L"young man"},
		{"Hernando Pizarro_Kind", L"good sir"},
		{"Gihat al-Din Jaqmaq_Kind", L"young lady"},
	} },
		{"OldBookMan", {
			{"Buy NoFlags" , L"Help, please help! I just saw something awful! A knight on horseback just killed a young couple and rode away! Who would do such a thing?! I came here to Bénouville to sell books, but I think I'll hide here in the bushes for now. Say, could I interest you in one of these?"},
			{"Sell NoFlags", L"*psst* Do you have any items you think I might like to buy? *whisper* What do you mean, why am I whispering? I just saw a madman butcher an innocent family, and I don't want to be next! Keep quiet!"},
			{"Buyback NoFlags", L"As a standing member of the Traders' Association I take part in the Merchant Buyback Scheme. If you've sold any item to us in the last 30 days we agree to-no I WON'T speak any louder, there's a killer on the loose!"},
			{"Buy MadKnightDefeated", L"Good evening to you, traveller. My name is Remy de Rouen. I came to Bénouville to sell books, but I'm not going anywhere near that town after all the horrible violence I've witnessed! I'm going back to Paris first thing in the morning! For now I shall be hiding in this bush. But if one of my books should interest you, I'd be more than happy to sell it for a fair price."},
			{"Sell MadKnightDefeated", L"I wouldn't mind taking a look at any valuables you might have acquired during your stay in Bénouville. I'll offer you a fair price!"},
			{"Buyback MadKnightDefeated", L"$DEFAULTBUYBACK$"},
		}},
		{ "MerchantNPC1", {
			{"Buy NoFlags" , L"Most merchants upped and left town as soon as those crazy villagers started killing people. I can't pretend that I stayed behind because of some noble intentions or loyalty to this town. Truth is, I just don't have anywhere to go. So are you interested in my wares or not?"},
			{"Sell NoFlags", L"If you have anything worth selling, I'll take a look. Based on what the other merchants are saying, you might be this town's last hope, so I'll give you a fair offer."},
			{"Buyback NoFlags", L"$DEFAULTBUYBACK$"},
		} },
		{ "MerchantNPC2", {
			{"Buy NoFlags" , L"Despite my dour colleague's dismal outlook, I stayed in Bénouville because I have hope for my future. After all, only some, not all, of the villagers were driven to madness. I don't know why that is, but rather than worry about it, I happily continue to sell my wares!"},
			{"Sell NoFlags", L"If you come across anything worth selling I'd be more than happy to take a look at it. And no, I haven't been turned mad yet. I'm just in a good mood."},
			{"Buyback NoFlags", L"$DEFAULTBUYBACK$"},
		} },
		{ "BSMITHM", {
			{"Buy NoFlags" , L"I have made weapons for all sorts of people in my time. The Burgundians, the Armagnacs, even the English. But now, my duty is to make weapons for whomever can save my beloved hometown from this terrible evil we face."},
			{"Sell NoFlags", L"If you have any items you no longer need, I'll take them off your hands."},
			{"Buyback NoFlags", L"$DEFAULTBUYBACK$"},
		} },
		{ "BSMITHF", {
			{"Buy NoFlags" , L"I have forged armour for all sorts of people in my time. The Ottomans, the Byzantines, even the Polish. But forget about all that. Right now I need to do my part to save this town, and that means offering my services at a fair rate."},
			{"Sell NoFlags", L"If you have any items you no longer need, I'll take them off your hands."},
			{"Buyback NoFlags", L"$DEFAULTBUYBACK$"},
		} },
		{ "IsobellaMerchant", {
			{"Buy NoFlags" , L"I've decided to sell my jewellery to raise the funds needed to help the town in its hour of need. For you I've laid out some items that have applications in combat. Please let me know if any of them interest you."},
			{"Sell NoFlags", L"If you have any items you no longer need, I'll take them off your hands."},
			{"Buyback NoFlags", L"$DEFAULTBUYBACK$"},
		} },
		{"DeadHorse", {
			{"1 Angela Fleuret", L"Hmph. I see the situation in Bénouville has become far worse than the one described in the letter."},
			{"2 Angela Fleuret", L"I must find my way into town... and pray I have not arrived too late to stop this."},
			{"1 Tianshun Song", L"This horse looks like it was healthy, well-fed, and full of life before its violent demise."},
			{"2 Tianshun Song", L"To kill it without using its remains for some purpose is such a waste."},
			{"1 Olyver Sumner", L"Good Lord! What on Earth's happened to that poor horse?!"},
			{"2 Olyver Sumner", L"Th-that's a sword sticking out of it! This was no accident..."},
			{"1 Hernando Pizarro", L"Díos mío, what a waste of a fine, healthy horse."},
			{"2 Hernando Pizarro", L"Stealing a man's horse is one thing, but killing it? How despicable."},
			{"1 Gihat al-Din Jaqmaq", L"Whoever killed this horse had no interest in sparing her any pain. Such an inefficient and barbaric wound would have greatly extended her suffering."},
			{"2 Gihat al-Din Jaqmaq", L"The madman who did this may still be close. I must proceed carefully."},
}},
		{"DeadWoman", {
				{"1 Angela Fleuret", L"This trail of carnage is an insult to the civilised world."},
				{"2 Angela Fleuret", L"Jesus give me the strength to extinguish this evil."},
				{"1 Tianshun Song", L"Another life destroyed with no rhyme or reason. How odd. Even the most barbaric Mongol invader kills with some goal in mind. To conquer a town, scare the weak peasants, or even just for the pleasure of killing."},
				{"2 Tianshun Song", L"But all this senseless, emotioness death feels so foreign to me. Killing with no hope or goal in mind. I need to find out more."},
				{"1 Olyver Sumner", L"Oh my God! That woman's been absolutely brutalised! What in God's name is happening in Bénouville?!"},
				{"2 Olyver Sumner", L"Oh I can't bear to look, I think I'm going to be sick!"},
				{"1 Hernando Pizarro", L"Looking at all this fills me with so much anger. Soldiers fighting in war is one thing, but I cannot abide the slaying of this innocent, defenceless woman."},
				{"2 Hernando Pizarro", L"Pity the soul of the man who did this without shame or remorse."},
				{"1 Gihat al-Din Jaqmaq", L"A poor, defenceless peasant woman. No weapon, no training, no hope of surviving whatever did this to you. If I had known you, I would have taught you how to wield a knife, at least."},
				{"2 Gihat al-Din Jaqmaq", L"... what am I saying? I don't have time to pity the dead. I need to keep moving."},
	}},
		{"DeadMan", {
				{"1 Angela Fleuret", L"These wounds are fresh, and by the looks of it, inflicted with a bladed weapon wielded with a great deal of strength."},
				{"2 Angela Fleuret", L"Whoever did this can't have gotten far. I will find him and put an end to him."},
				{"1 Tianshun Song", L"This man's life force was cut short very recently, I can feel it."},
				{"2 Tianshun Song", L"Perhaps if I'd gotten here quicker I could have seen who did it."},
				{"1 Olyver Sumner", L"Even if I turned around now, I could never hope the reach the nearest town before sunset. Then I would be alone in the dark with whatever freak of nature did these terrible things. Look at me... I'm so scared, I'm shaking."},
				{"2 Olyver Sumner", L"N-no! I won't be afraid! I will fight if I have to!"},
				{"1 Hernando Pizarro", L"No survivors so far. Díos... is the rest of the town like this?!"},
				{"2 Hernando Pizarro", L"No matter. If I find the man responsible for this, I will bring swift justice to him, or my name isn't Hernando Pizarro!"},
				{"1 Gihat al-Din Jaqmaq", L"These wounds are fresh. This can't have happened that long ago."},
				{"2 Gihat al-Din Jaqmaq", L"I must keep my wits about me in this town. As long as I maintain my composure, this carnage won't become a distraction."},
	}},
		{"Fireplace1", {
				{"1 Angela Fleuret", L"My journey here from the Vatican was one of speed rather than comfort. 'Tis a welcome change of pace to finally be somewhere warm and dry with a simple fireplace and the smell of cooking."},
				{"1 Tianshun Song", L"I felt the pull of this town's negative energy all the way from Paris and I haven't rested since. Perhaps I could close my eyes just for a moment..."},
				{"1 Olyver Sumner", L"What a lovely hearth. If I wasn't haunted by the idea of a psycho killer hiding upstairs I'd probably lie down and rest my eyes."},
				{"1 Hernando Pizarro", L"Ah... to lay by such a fire with a glass of wine, a good friend and passionate conversation... maybe another time."},
				{"1 Gihat al-Din Jaqmaq", L"I shouldn't be wasting any more time standing in this dead peasant's house!"},
	}},
		{ "Leave Bénouville", {
			{"1 Angela Fleuret", L"I cannot leave until my work here is done."},
			{"1 Tianshun Song", L"It would be easy for me to walk away, but the dark energy of this place would just call me back."},
			{"1 Olyver Sumner", L"I will return to England, but not yet. There is more here I must accomplish."},
			{"1 Hernando Pizarro", L"A gentleman never cuts and runs. I will stay here for as long as I am needed."},
			{"1 Gihat al-Din Jaqmaq", L"I'm not going home empty handed. There is more I must do here."},
	}},
		{ "HorsemanCutscene1", {
		{"1 PLAYER", L"!!!"},
		{"1.01 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_WALK_RIGHT"},
		{"1.02 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_WALK_RIGHT"},
		{"1.1 $MOVEOBJECTS$", L"PLAYER1$47.5,10,GRASS$50"}, // object_where_soundToPlay
		{"1.2 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_STAND_RIGHT"},
		{"1.3 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_STAND_RIGHT"},
		{"2 Angela Fleuret", L"You! Stop at once!"},
		{"2 Tianshun Song", L"You must be... yes. I sense it."},
		{"2 Olyver Sumner", L"Y-you there! Who are you?!"},
		{"2 Hernando Pizarro", L"You! The one whose blade is bathed in the blood of innocents!"},
		{"2 Gihat al-Din Jaqmaq", L"Step aside, rider! Do not get in my way!"},
		{"3 $STOPDIALOGUE$", L""},
		{"4 $LOADOBJECT$", L"White Knight_68_10_6_500_White Knight_STAND_LEFT_2.0_1.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer_anchor
		{"5 $LOADOBJECT$", L"Shadow White Knight_68_10_5_500_Shadow White Knight_STAND_LEFT_2.0_0.5_0_CENTRE"},
		{"6 $ANIMATEOBJECT$", L"White Knight_White Knight_WALK_LEFT"}, // imageName, character, action, direction
		{"7 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_WALK_LEFT"},
		{"8 $MOVEOBJECTS$", L"White Knight_Shadow White Knight_CAMERA$60,10,HORSE_60,10,NOAUDIO_54,10,NOAUDIO$50"}, // object_where_soundToPlay
		{"9 $ANIMATEOBJECT$", L"White Knight_White Knight_STAND_LEFT"},
		{"10 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_STAND_LEFT"},
		{"11 $WAIT$", L"wait_100"},
		{"12 $PLAYSFX$", L"1049_0_1"},
		{"13 $PLAYSFX$", L"1050_0_1"},
		{"14 $ANIMATEOBJECT$", L"White Knight_White Knight_REAR_LEFT"},
		{"15 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_REAR_LEFT"},
		{"16 $CHANGEANIMATIONSPEED$", L"White Knight_Shadow White Knight$80$SINGLE"}, //what_what$speed$styles
		{"17 $WAITFORANIMATION$", L"White Knight"},
		{"18 $ANIMATEOBJECT$", L"White Knight_White Knight_STAND_LEFT"},
		{"19 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_STAND_LEFT"},
		{"20 $CHANGEANIMATIONSPEED$", L"White Knight_Shadow White Knight$500$LOOP"}, //what_what$speed$styles
		{"21 $WAIT$", L"wait_100"},
		{"22 White Knight?$DIRECT$", L"ISOBELLA!!!"},
		{"23 White Knight?$DIRECT$", L"IIIIIISSSOOOOOBBBEEEEEELLLLAAAAAAAAAAAAAA!!! COME OUT AND FACE WHAT YOU'VE MADE ME DO!"},
		{"24 Angela Fleuret", L"You there, rider! I demand you stop this at once! Do you hear me?!"},
		{"25 Angela Fleuret", L"Lay down your sword and dismount peacefully, or I will be required to use force!"},
		{"24 Tianshun Song", L"I was right about you after all. You kill for neither gain nor goal. You kill because madness compels you."},
		{"25 Tianshun Song", L"He who kills without purpose is despicable. Get away from me, or perish!"},
		{"24 Olyver Sumner", L"I... I feel as though I have stepped into a page from Vox Clamantis. A world of madness, rage and demons."},
		{"25 Olyver Sumner", L"I warn you, rider! I will defend myself if you try to attack me!"},
		{"24 Hernando Pizarro", L"You crazy bastard! You have spilled the blood of the defenceless for no reason but to sate your own insatiable insanity! Come forth and I will strike you down!"},
		{"25 Hernando Pizarro", L"Hey! You! I'm talking to you! Do not ignore me, you honourless cur!"},
		{"24 Gihat al-Din Jaqmaq", L"This Isobella 'made' you kill all these people? Is she really that persuasive, or are you just the most guillable idiot France has to offer?"},
		{"25 Gihat al-Din Jaqmaq", L"Hello? Are you even listening to me?"},
		{"26 $WAIT$", L"wait_100"},
		{"27 Father Michelet?$DIRECT$", L"NO! STOP! STAY BACK!"},
		{"28 $LOADOBJECT$", L"Father Michelet_52.5_0_6_500_Father Michelet_STAND_FRONT_0.9_1.0_0_CENTRE"},
		{"29 $LOADOBJECT$", L"Shadow Father Michelet_52.5_0_5_500_Shadow Father Michelet_STAND_FRONT_0.9_0.5_0_CENTRE"},
		{"30 $LOADOBJECT$", L"Isobella de Vaines_55_0_6_500_Isobella de Vaines_STAND_FRONT_0.9_1.0_0_CENTRE"},
		{"31 $LOADOBJECT$", L"Shadow Isobella de Vaines_55_0_5_500_Shadow Isobella de Vaines_STAND_FRONT_0.9_0.5_0_CENTRE"},
		{"32 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
		{"33 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
		{"34 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_FRONT"},
		{"35 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_WALK_FRONT"},
		{"36 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet_Isobella de Vaines_Shadow Isobella de Vaines$-1,4.5,STONE_-1,4.5,NOAUDIO_-1,4.5,NOAUDIO_-1,4.5,NOAUDIO$50"},
		{"37 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
		{"38 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
		{"39 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"40 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_FRONT"},
		{"41 Father Michelet?$DIRECT$", L"My $POLITE$, in the name of the Lord I beg you to stay back!"},
		{"42 Father Michelet?$DIRECT$", L"That knight is on an uncontrollable rampage and I fear he will do with you as he has done with so many others!"},
		{"43 $ANIMATEOBJECT$", L"White Knight_White Knight_WALK_LEFT"}, 
		{"44 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_WALK_LEFT"},
		{"45 $MOVEOBJECTS$", L"White Knight_Shadow White Knight$55,10,HORSE_55,10,HORSE$50"},
		{"46 $ANIMATEOBJECT$", L"White Knight_White Knight_STAND_LEFT"},
		{"47 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_STAND_LEFT"},
		{"48 Isobella de Vaines?$DIRECT$", L"That poor $KIND$ is going to die..."},
		{"49 Isobella de Vaines?$DIRECT$", L"I can't... I can't let this keep happening."},
		{"50 Isobella de Vaines?$DIRECT$", L"NO! STOP THIS! NO MORE!"},
		{"51 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_FRONT"},
		{"52 $MOVEOBJECTS$", L"Isobella de Vaines_Shadow Isobella de Vaines$-1,7,STONE_-1,7,NOAUDIO$50"},
		{"53 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"54 Isobella de Vaines?$DIRECT$", L"I'M THE ONE YOU WANT! LEAVE $GENDERUPPER$ ALONE!"},
		{"55 Father Michelet?$DIRECT$", L"Isobella, don't! Don't do this, he won't listen-"},
		{"56 Isobella de Vaines?$DIRECT$", L"No! I can't take it anymore! Listen to me, William! Please! I am your wife! If killing me will truly abate your bloodlust then do it, just leave $GENDER$ be!"},
		{"57 White Knight?$DIRECT$", L"..."},
		{"58 White Knight?$DIRECT$", L"My... wife?"},
		{"59 White Knight?$DIRECT$", L"You think you can betray our holy vows by whoring yourself to this priest only to spit on my face with the word 'wife'?"},
		{"60 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_FRONT"},
		{"61 $MOVEOBJECTS$", L"Isobella de Vaines_Shadow Isobella de Vaines$-1,6,STONE_-1,6,NOAUDIO$50"},
		{"62 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"63 Isobella de Vaines?$DIRECT$", L"I clearly remember those vows better than you do, because I have never betrayed them! I have always loved you and been faithful to you! I am a good wife, why are you-"},
		{"64 White Knight?$DIRECT$", L"LIAR! WHORE! I KNOW EVERYTHING BECAUSE THE TRUTH WAS SHOWN TO ME BY A SERVANT OF GOD!"},
		{"65 White Knight?$DIRECT$", L"Mark my words, Isobella. I will revel in putting you to the sword, but not before I make you watch me cut down every man, woman, and child who knew of your deception and kept the truth from me!"},
		{"66 White Knight?$DIRECT$", L"Because of you they mocked me! Laughed at my emasculation! Made a fool out of me while you sought unholy bindings of flesh with that PRIEST!"},
		{"67 White Knight?$DIRECT$", L"I'll make you watch me tear him limb from limb!"},
		{"68 Angela Fleuret", L"That's enough, mad rider. I fear neither you nor death. In the name of the Lord I shall end your spell of madness!"},
		{"69 Tianshun Song", L"Mad rider, your motives for killing simply aren't good enough to justify what you've done. But mine are."},
		{"70 Olyver Sumner", L"You will do no such thing, mad rider! Your torture of these innocent people ends right now!"},
		{"71 Hernando Pizarro", L"ENOUGH! Mad rider, if you so wish to whet your blade then I will give you a worthy foe to face!"},
		{"72 Gihat al-Din Jaqmaq", L"These theatrics are a waste of my time. Mad rider, you are out of control, but more importantly, you are in my way!"},
		{"73 $STOPDIALOGUE$", L""},
		{"74 $FROMCUTSCENETOMENU$", L"TUTORIALCONFIRM"},
	} },
		{ "HorsemanCutscene2$Angela Fleuret", {
			{"1 $WAIT$", L"wait_400"},
			{"3 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"4 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"5 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$200$SINGLE"},
			{"5.1 $PLAYSFX$", L"1055_0_1"},
			{"6 $WAITFORANIMATION$", L"PLAYER1_Explore"},
			{"7 Angela Fleuret", L"By the grace and glory of the almighty God, I pray for victory in my actions! Please, God, hear my cry in your honour as I call upon your strength! HEAVENSTRIKE!"},
			{"7.1 $STOPDIALOGUE$", L""},
			{"8 $LOADOBJECT$", L"Heavenstrike_0_0_5_50_Heavenstrike1_ACTION_1_2.0_1.0_1_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"8.1 $PLAYSFX$", L"1056_0_1"},
			{"9 $CHANGEANIMATIONSPEED$", L"Heavenstrike$40$SINGLE"},
			{"10 $WAITFORANIMATION$", L"Heavenstrike"},
			{"11 $LOADOBJECT$", L"Heavenstrike2_56_0.5_11_50_Heavenstrike2_ACTION_1_2.0_1.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"11.1 $PLAYSFX$", L"1057_0_1"},
			{"12 $ANIMATEOBJECT$", L"Heavenstrike_Heavenstrike1_ACTION_2"},
			{"12.1 $CHANGEANIMATIONSPEED$", L"Heavenstrike$20$SINGLE"},
			{"13 $CHANGEANIMATIONSPEED$", L"Heavenstrike2$80$SINGLE"},
			{"14 $WAITFORANIMATION$", L"Heavenstrike2"},
			{"15 $REMOVEIMAGES$", L"Heavenstrike2"},
			{"16 $WAITFORANIMATION$", L"Heavenstrike"},
			{"17 $REMOVEIMAGES$", L"Heavenstrike"},
			{"18 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene3"},
		}},
		{ "HorsemanCutscene2$Tianshun Song", {
		{"1 $WAIT$", L"wait_400"},
		{"3 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_RIGHT"},
		{"4 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_RIGHT"},
		{"5 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$200$SINGLE"},
		{"5.1 $PLAYSFX$", L"1055_0_1"},
		{"6 $WAITFORANIMATION$", L"PLAYER1_Explore"},
		{"7 Tianshun Song", L"I command the blood in your veins to bend to my will! May your life energy wither while mine flourishes! LIFE DRAIN!"},
		{"7.1 $STOPDIALOGUE$", L""},
		{"8 $HANDLESKILLANIMATION$", L"Tianshun Song_Explore$White Knight$Life Drain$xOffset%5"},
		{"20 $WAIT$", L"wait_400"},
		{"18 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene3"},
		} },
		{ "HorsemanCutscene2$Hernando Pizarro", {
		{"1 $WAIT$", L"wait_400"},
		{"3 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_RIGHT"},
		{"4 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_RIGHT"},
		{"5 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$200$SINGLE"},
		{"5.1 $PLAYSFX$", L"1061_0_1"},
		{"6 $WAITFORANIMATION$", L"PLAYER1_Explore"},
		{"7 Hernando Pizarro", L"By the strength of my blade and the skills time has seen fit to grant me, I will cut you down where you stand! FINE STRIKE!"},
		{"7.1 $STOPDIALOGUE$", L""},
		{"8 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONATTACK_R1"},
		{"9 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONATTACK_R1"},
		{"10 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$20$SINGLE"},
		{"10.1 $LOADOBJECT$", L"FineStrike1_0_0_5_50_FineStrike1_ACTION_1_2.0_1.0_1_CENTRE"},
		{"10.2 $LOADOBJECT$", L"FineStrike2_0_0_10_50_FineStrike2_ACTION_1_2.0_1.0_1_CENTRE"},
		{"10.25 $PLAYSFX$", L"1062_54100_1"},
		{"10.3 $CHANGEANIMATIONSPEED$", L"FineStrike1$60$SINGLE"},
		{"10.4 $CHANGEANIMATIONSPEED$", L"FineStrike2$60$SINGLE"},
		{"11 $WAITFORANIMATION$", L"FineStrike1"},
		{"12 $CHANGEANIMATIONSPEED$", L"FineStrike1$10$SINGLE_FADEOUT"},
		{"13 $CHANGEANIMATIONSPEED$", L"FineStrike2$10$SINGLE_FADEOUT"},
		{"20 $WAIT$", L"wait_400"},
		{"21 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene3"},
		} },
		{ "HorsemanCutscene2$Olyver Sumner", {
			{"1 $WAIT$", L"wait_400"},
			{"3 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"4 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"5 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$200$SINGLE"},
			{"5.1 $PLAYSFX$", L"1055_0_1"},
			{"6 $WAITFORANIMATION$", L"PLAYER1_Explore"},
			{"7 Olyver Sumner", L"By the wisdom of Aristotle, I command the wind and skies to do their bidding upon thee! May they see fit to blast you asunder as you deserve! PLASMA PULSE!"},
			{"7.1 $STOPDIALOGUE$", L""},
			{"8 $LOADOBJECT$", L"PlasmaPulse1_0_0_5_50_PlasmaPulse1_ACTION_1_2.0_1.0_1_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"9 $LOADOBJECT$", L"PlasmaPulse2_48.5_8.2_7_50_PlasmaPulse2_ACTION_1_0.5_1.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"10 $PLAYSFX$", L"1058_0_1"},
			{"11 $CHANGEANIMATIONSPEED$", L"PlasmaPulse1$40$SINGLE"},
			{"12 $CHANGEANIMATIONSPEED$", L"PlasmaPulse2$40$FADEIN_LOOP"},
			{"13 $WAITFORANIMATION$", L"PlasmaPulse1"},
			{"15 $PLAYSFX$", L"1059_0_1"},
			{"16 $LOADOBJECT$", L"PlasmaPulse3_53_8_7_50_PlasmaPulse3_ACTION_1_0.8_1.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"17 $CHANGEANIMATIONSPEED$", L"PlasmaPulse3$40$SINGLE"},
			{"18 $WAITFORANIMATION$", L"PlasmaPulse3"},
			{"19 $REMOVEIMAGES$", L"PlasmaPulse1$PlasmaPulse2$PlasmaPulse3"},
			{"20 $WAIT$", L"wait_400"},
			{"21 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene3"},
		} },
		{ "HorsemanCutscene2$Gihat al-Din Jaqmaq", {
			{"1 $WAIT$", L"wait_400"},
			{"3 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"4 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_RIGHT"},
			{"5 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$200$SINGLE"},
			{"5.1 $PLAYSFX$", L"1051_0_1"},
			{"6 $WAITFORANIMATION$", L"PLAYER1_Explore"},
			{"10 Gihat al-Din Jaqmaq", L"By the wisdom of Allah I wield these blades to spread sorrow to my enemies! DOUBLE STRIKE!"},
			{"10.1 $STOPDIALOGUE$", L""},
			{"11.1 $PLAYSFX$", L"1052_0_1"},
			{"11.2 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFADE_RIGHT"},
			{"11.3 $CHANGEANIMATIONSPEED$", L"Shadow PLAYER1$200$FADEOUT"},
			{"12 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFADE_RIGHT"},
			{"14 $WAITFORANIMATION$", L"PLAYER1_Explore"},
			{"15 $CHANGEOPACITY$", L"Gihat al-Din Jaqmaq_Explore$0.0"},
			{"16 $WAIT$", L"wait_400"},
			{"17 $LOADOBJECT$", L"Gihat Attacking_55_0_6_50_Gihat al-Din Jaqmaq_MAPACTIONATTACK_FRONT_1.0_0.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"18 $CHANGEANIMATIONSPEED$", L"Gihat Attacking$50$SINGLE_FADEIN"},
			{"19 $MOVEOBJECTS$", L"Gihat Attacking$55,10,NOAUDIO$10"},
			{"19.01 $PLAYSFX$", L"1053_44100_1"},
			{"19.1 $LOADOBJECT$", L"Doublestrike_55_10_7_50_Doublestrike_ACTION_FRONT_2.0_1.0_0_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
			{"19.2 $CHANGEANIMATIONSPEED$", L"Doublestrike$50$SINGLE_FADEOUTWHENFINISHED"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity
			{"20 $CHANGEANIMATIONSPEED$", L"Gihat Attacking$50$SINGLE_FADEOUT"},
			{"21 $MOVEOBJECTS$", L"Gihat Attacking$55,15,NOAUDIO$10"},
			{"22 $WAITFORANIMATION$", L"Gihat Attacking"},
			{"23 $WAIT$", L"wait_100"},
			{"30 $ANIMATEOBJECT$", L"PLAYER1_Gihat al-Din Jaqmaq_MAPACTIONFADEBACKIN_RIGHT"},
			{"25.1 $PLAYSFX$", L"1054_0_1"},
			{"25.6 $CHANGEOPACITY$", L"Gihat al-Din Jaqmaq_Explore$1.0"},
			{"25.6 $CHANGEOPACITY$", L"Gihat al-Din Jaqmaq_Shadow$0.5"},
			{"31 $CHANGEANIMATIONSPEED$", L"PLAYER1$200$SINGLE_FADEIN"},
			{"31 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow$200$LOOP"},
			{"34 $WAIT$", L"wait_100"},
			{"35 $CHANGEOPACITY$",  L"Gihat al-Din Jaqmaq_Shadow$0.5"},
			{"36 $REMOVEIMAGES$", L"Doublestrike"},
			{"52 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene3"},
		}},
		{ "HorsemanCutscene3", {
			{"33 $PLAYSFX$", L"1050_0_1"},
			{"35 $ANIMATEOBJECT$", L"White Knight_White Knight_REAR_LEFT"},
			{"36 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_REAR_LEFT"},
			{"37 $CHANGEANIMATIONSPEED$", L"White Knight_Shadow White Knight$80$SINGLE"}, //what_what$speed$styles
			{"38 $WAITFORANIMATION$", L"White Knight"},
			{"39 $ANIMATEOBJECT$", L"White Knight_White Knight_WALK_FRONT"},
			{"40 $ANIMATEOBJECT$", L"Shadow White Knight_Shadow White Knight_WALK_FRONT"},
			{"41 $CHANGEANIMATIONSPEED$", L"White Knight_Shadow White Knight$500$LOOP"}, //what_what$speed$styles
			{"41.5 $MOVEOBJECTS$", L"White Knight_Shadow White Knight$-1,15,HORSE_-1,15,NOAUDIO$30"}, // object_where_soundToPlay
			{"42 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHT_FRONT"},
			{"42.5 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHT_FRONT"},
			{"43 $MOVEOBJECTS$", L"White Knight_Shadow White Knight$-1,30,HORSE_-1,30,NOAUDIO$30"}, // object_where_soundToPlay
			{"44 $WAIT$", L"wait_100"},
			{"45 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_MAPACTIONFIGHTUNDO_FRONT"},
			{"46 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_MAPACTIONFIGHTUNDO_FRONT"},
			{"47 $WAITFORANIMATION$", L"PLAYER1_Explore"},
			{"48 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_STAND_FRONT"},
			{"49 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_STAND_FRONT"},
			{"50 $CHANGEANIMATIONSPEED$", L"PLAYER1_Shadow PLAYER1$500$LOOP"},
			{"51 $WAIT$", L"wait_100"},
			{"52 $REMOVEIMAGES$", L"White Knight$Shadow White Knight"},
			{"53 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_FRONT"},
			{"54 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_WALK_FRONT"},
			{"55 $MOVEOBJECTS$", L"Isobella de Vaines_Shadow Isobella de Vaines$-1,9.25,GRASS_-1,9.25,NOAUDIO$20"},
			{"56 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_LEFT"},
			{"57 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_WALK_LEFT"},
			{"58 $MOVEOBJECTS$", L"Isobella de Vaines_Shadow Isobella de Vaines$50,-1,GRASS_50,-1,NOAUDIO$20"},
			{"59 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_LEFT"},
			{"60 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_LEFT"},
			{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene4$PLAYER"},
}},
		{ "HorsemanCutscene4$Gihat al-Din Jaqmaq", {
		{"1 Isobella de Vaines?$DIRECT$", L"Are you okay m'lady?! I'm so sorry about all of this..."},
		{"2 Gihat al-Din Jaqmaq", L"That husband of yours sure is a miserable bastard. If Christian nations permit divorce, now would be the time to go and get one."},
		{"3 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"4 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_FRONT"},
		{"5 Isobella de Vaines?$DIRECT$", L"Whatever that thing has become, that's not the man I married. Not anymore..."},
		{"6 Isobella de Vaines?$DIRECT$", L"I am afraid he is but the latest in a line of many in this town who have become stricken with unending madness..."},
		{"6.1 Gihat al-Din Jaqmaq", L"I beg your pardon?"},
		{"7 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
		{"8 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
		{"9 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$-1,7,GRASS_-1,7,NOAUDIO$20"},
		{"10 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_LEFT"},
		{"11 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_LEFT"},
		{"12 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$47.5,-1,GRASS_47.5,-1,NOAUDIO$20"},
		{"13 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
		{"14 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
		{"15 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_LEFT"},
		{"16 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_LEFT"},
		{"17 Father Michelet$DIRECT$", L"M'lady, I am Father Michelet. And this is Isobella de Vaines."},
		{"18 Father Michelet$DIRECT$", L"I am afraid you have chosen a most ill-timed moment to come to our town. If you wish to turn around and leave we will not question you."},
		{"19 Gihat al-Din Jaqmaq", L"I don't care about whatever family drama crap you have going on here. I'm not leaving until I get what I came for."},
		{"20 Isobella de Vaines$DIRECT$", L"What you came for? Who... are you, exactly?"},
		{"20.1 $ANIMATEOBJECT$", L"PLAYER1_Gihat al-Din Jaqmaq_STAND_RIGHT"},
		{"21 Gihat al-Din Jaqmaq", L"I am Gihat al-Din of House Jaqmaq. I have been sent here on a mission to find one of my fellow countrymen, an Egyptian by the name of Nasir al-Shafi-i."},
		{"22 Gihat al-Din Jaqmaq", L"His last letter indicated he was in this town, and we have since lost contact with him."},
		{"23 Isobella de Vaines$DIRECT$", L"...?"},
		{"24 Isobella de Vaines$DIRECT$", L"You are looking for an Egyptian named... I beg your pardon, but I am not familiar with Moorish names."},
		{"24.1 $ANIMATEOBJECT$", L"PLAYER1_Gihat al-Din Jaqmaq_STAND_FRONT"},
		{"25 Gihat al-Din Jaqmaq", L"(Tch! I made my handmaiden teach me French just for this mission and these stupid peasants can't even understand me! Allah give me patience to withstand this country's people!)"},
		{"25.1 $ANIMATEOBJECT$", L"PLAYER1_Gihat al-Din Jaqmaq_STAND_RIGHT"},
		{"26 Gihat al-Din Jaqmaq", L"Not Moorish. Egyptian. NA-SEER AL-SHAFE-EE."},
		{"27 Isobella de Vaines$DIRECT$", L"Um... I see, well... we have had a few travellers come to Bénouville recently, but I do not remember a gentleman from Egypt with such a name."},
		{"28 Gihat al-Din Jaqmaq", L"Very well. Then I must take my leave and search for him myself."},
		{"29 Father Michelet$DIRECT$", L"M'lady, wait! I don't think you understand!"},
		{"29.1 $ANIMATEOBJECT$", L"PLAYER1_Gihat al-Din Jaqmaq_STAND_BACK"},
		{"30 Father Michelet$DIRECT$", L"Our town is not safe. Forces beyond our understanding have driven many of the townspeople to violent madness as you have just seen before your very eyes!"},
		{"31 Father Michelet$DIRECT$", L"The one you seek may very well have been caught up in the chaos."},
		{"32 Father Michelet$DIRECT$", L"If you insist on staying in Bénouville we beg of you... come with us for a moment so we may warn you about what lies ahead."},
		{"33 Father Michelet$DIRECT$", L"If you wish to leave at that point we will understand. But if you do press ahead at least you will be better prepared than those who ignored us before."},
		{"34 Gihat al-Din Jaqmaq", L"..."},
		{"35 Gihat al-Din Jaqmaq", L"I can't possibly imagine what is driving your townspeople to commit such heinous acts. (Aside from the lack of education and dignity that defines the peasants of Europe...) Lead the way, I will listen to what you have to say."},
		{"69 $STOPDIALOGUE$", L""},
		{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene5"},
} },
		{ "HorsemanCutscene4$Angela Fleuret", {
			{"0 $ANIMATEOBJECT$", L"PLAYER1_Angela Fleuret_STAND_RIGHT"},
			{"1 Isobella de Vaines?$DIRECT$", L"I'm so sorry, I'm so sorry! Are you alright, dear lady?!"},
			{"2 Angela Fleuret", L"Your concern is touching, but it is not required. An opponent of such low calibre is no threat to me."},
			{"3 Father Michelet?$DIRECT$", L"That holy light..."},
			{"4 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
			{"5 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
			{"6 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$-1,7,GRASS_-1,7,NOAUDIO$20"},
			{"7 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_LEFT"},
			{"8 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_LEFT"},
			{"9 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$47.5,-1,GRASS_47.5,-1,NOAUDIO$20"},
			{"10 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
			{"11 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
			{"12 Father Michelet?$DIRECT$", L"Are you... the one? No... you can't be... can you?"},
			{"13 $ANIMATEOBJECT$", L"PLAYER1_Angela Fleuret_STAND_BACK"},
			{"14 Angela Fleuret", L"I could be. 'Cept you haven't specified which 'one' it is you think I am."},
			{"15 Father Michelet?$DIRECT$", L"Well, I, uh...  you see..."},
			{"16 Father Michelet?$DIRECT$", L"I... no, we... sent a letter to the Vatican..."},
			{"17 Angela Fleuret", L"A letter which his Holiness Pope Callixtus and I read very carefully. The fact I have travelled here with such urgency to meet you should be proof of that."},
			{"18 Angela Fleuret", L"Though perhaps not proof enough, given by that dumbfounded look on your face."},
			{"19 Father Michelet?$DIRECT$", L"When I prayed for the church to send aid, I did not imagine it would come in the form of a, well..."},
			{"20 Angela Fleuret", L"A what exactly? An old maid? Rest assured I haven't forgotten who or what I am. But do not mistake my age for weakness, nor my womanhood for compassion."},
			{"21 Angela Fleuret", L"If you should assume anything from those two facts, it is that I have defied all expectations to accumulate decades of expertise in the subject of vanquishing evil, and that I do so with a heart full of faith in God and his hopes for humanity."},
			{"22 Angela Fleuret", L"Now then, seeing as the situation in Bénouville is clearly far worse than it was when you penned your letter, I assume we make any more pleasantries as swift as possible."},
			{"23 Angela Fleuret", L"I am Angela Fleuret. And I am left to assume you two are Father Michelet and Isobella de Vaines."},
			{"24 Isobella de Vaines$DIRECT$", L"Yes, indeed."},
			{"25 Angela Fleuret", L"Very well. If you still require my assistance, may I suggest we all go somewhere safer than out in the open to discuss the situation? Or if you prefer to handle your affairs without me, I shall make my leave."},
			{"26 Father Michelet$DIRECT$", L"I unreservedly apologise for the misunderstanding, Mother Fleuret."},
			{"27 Angela Fleuret", L"Oh for the love of Jesus... don't call me Mother. I am a Cardinal, not a Nun. Why don't you just call me Angela?"},
			{"28 Father Michelet$DIRECT$", L"Of course, Angela. I'm sorry."},
			{"29 Father Michelet$DIRECT$", L"The villagers have established a safe zone in the town square. Please, come with us and we can discuss things safely there."},
			{"30 Angela Fleuret", L"Lead the way."},
			{"69 $STOPDIALOGUE$", L""},
			{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene5"},
		} },
		{ "HorsemanCutscene4$Tianshun Song", {
		{"1 Isobella de Vaines?$DIRECT$", L"Oh my goodness... you poor little girl! What are you doing out here all alone? Where is your Mama?"},
		{"2 Tianshun Song", L"..."},
		{"3 $ANIMATEOBJECT$", L"PLAYER1_Tianshun Song_STAND_RIGHT"},
		{"4 Tianshun Song", L"'Poor little girl?' 'Mama?' Did you not just see that I am more than capable of looking after myself?!"},
		{"5 Isobella de Vaines?$DIRECT$", L"But you're... you're just a little girl."},
		{"6 Tianshun Song", L"Maybe so. But that's not all I am!"},
		{"7 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
		{"8 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
		{"9 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$-1,7,GRASS_-1,7,NOAUDIO$20"},
		{"10 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_LEFT"},
		{"11 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_LEFT"},
		{"12 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$47.5,-1,GRASS_47.5,-1,NOAUDIO$20"},
		{"13 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
		{"14 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
		{"15 $ANIMATEOBJECT$", L"PLAYER1_Tianshun Song_STAND_BACK"},
		{"16 Father Michelet?$DIRECT$", L"Tell me, young lady... what is your name?"},
		{"17 Tianshun Song", L"..."},
		{"18 Tianshun Song", L"My name is not something I give out carelessly to strangers."},
		{"19 Father Michelet$DIRECT$", L"Okay, well... how about we tell you our names first, okay? I'm Michelet, and this is Isobella."},
		{"20 Tianshun Song", L"............"},
		{"21 Tianshun Song", L"If capitulating will make this go faster, fine. You may call me Tianshun. If you can't pronounce it properly that's not my problem."},
		{"22 Father Michelet$DIRECT$", L"Dian...Jian... Sh... (Hmm...) Tian...shun. How's that?"},
		{"23 Tianshun Song", L"............"},
		{"24 Father Michelet$DIRECT$", L"It's very nice to meet you, Tianshun. You seem like a smart young lady, so I suppose you wouldn't have a hard time understanding that right now... our town is not a safe place to visit."},
		{"25 Tianshun Song", L"I know. It's why I'm here, after all."},
		{"26 Isobella de Vaines$DIRECT$", L"You're here because of our troubles? Wait... do you already know what's going on?"},
		{"27 Tianshun Song", L"I doubt any explaination will result in any understanding on your part, but very well. I am a student of death. A practitioner of blood magic. A servant of no god, no deity, and no religion."},
		{"31 Tianshun Song", L"Does this not shock you?"},
		{"32 Isobella de Vaines$DIRECT$", L"I only feel great sadness to see a child turn away from God. But please... go on."},
		{"33 Tianshun Song", L"My studies allow me to sense the flow of certain... otherworldly energies. For example, the one that has been overflowing from your town for the past week. It calls to me in my dreams from hundreds of miles away."},
		{"33.1 Isobella de Vaines$DIRECT$", L"You... you could really sense something was wrong with this town from so far away?!"},
		{"34 Tianshun Song", L"My understanding so far is that this energy is fuelled by hatred and violence, but I know not its origin, nor its purpose."},
		{"34.1 Tianshun Song", L"That's why I have come here. I am compelled to study such a force and understand its true meaning."},
		{"35 Father Michelet$DIRECT$", L"Tianshun, I can't pretend to understand why it is you would pursue such a goal..."},
		{"36 Father Michelet$DIRECT$", L"But what would you say if we... asked for your help?"},
		{"37 Isobella de Vaines$DIRECT$", L"For shame, Father Michelet, she is just a child who has lost her way!"},
		{"38 Father Michelet$DIRECT$", L"That may be so, but she seems very capable of making her own decisions."},
		{"39 Tianshun Song", L"My help? You want my help?"},
		{"40 Father Michelet$DIRECT$", L"If you are, as you say, sensitive to the dark energy that overruns Bénouville, I will give you my full support in exploring its origins and learning whatever you wish about it."},
		{"42 Father Michelet$DIRECT$", L"My only condition is that once your curiosity about the nature of this evil is satisfied, that you vanquish it at once."},
		{"43 Tianshun Song", L"I agree to these terms. I will free you from the burden of this otherworldly interference, so long as in return, you do not get in my way."},
		{"44 Father Michelet$DIRECT$", L"Of course. If you wish... I would like to invite you to join us. The villagers have set up a safe zone in the middle of town. You can safely rest there, and we can fill you in on what we've learned so far."},
		{"45 Tianshun Song", L"Lead the way. But remember, holyman, that while I may be young, my knowledge of dark magic is more than enough to protect me from any betrayal you may conjure up in your mind."},
		{"46 Isobella de Vaines$DIRECT$", L"Betrayal? Dark energies? What in God's name happened to this poor little girl to make her turn out this way...?"},
		{"69 $STOPDIALOGUE$", L""},
		{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene5"},
	}},
		{ "HorsemanCutscene4$Olyver Sumner", {
		{"1 Isobella de Vaines?$DIRECT$", L"I'm so sorry... I'm so sorry about all of this. Are you alright, sir?"},
		{"2 Olyver Sumner", L"AHAHAHA! I am more than alright! I am bloody BRILLIANT!"},
		{"2.1 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_LEFT"},
		{"2.2 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_WALK_LEFT"},
		{"2.3 $MOVEOBJECTS$", L"Isobella de Vaines_Shadow Isobella de Vaines$50.5,-1,GRASS_50.5,-1,NOAUDIO$50"},
		{"2.4 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_LEFT"},
		{"2.5 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_LEFT"},
		{"3 $ANIMATEOBJECT$", L"PLAYER1_Olyver Sumner_STAND_RIGHT"},
		{"4 Olyver Sumner", L"You see, I've never actually had recourse to cast a spell on a person before, I mean a live person, I mean a live human, well, I mean, in combat, I mean... it worked splendidly, did it not?! Ahaha! I am truly realising my potential! What a wonderful day! Well... except for the corpses and bad language and all that, but still!"},
		{"4.1 Isobella de Vaines?$DIRECT$", L"Are you quite sure you are well? You seem to be shaking."},
		{"4.2 Olyver Sumner", L"Oh I'll be fine I assure you. It's just the nerves. I was quite terrified, actually. Scared witless! Thought I was going to die! But I didn't, I had my spell ready and I said no sir, not today! And then I... *sniff*"},
		{"4.3 Isobella de Vaines?$DIRECT$", L"And now you're crying..."},
		{"4.4 Olyver Sumner", L"I'm fine, I'm *sniff* I'm fine. It's just the nerves. I almost died! I could have been skewered, but I wasn't. I'm fine..."},
		{"4.5 Olyver Sumner", L"I'm sorry it's just... I'm not really much of a fighter. I'm more of a book person, really..."},
		{"5 Olyver Sumner", L"Ahem... forgive me... it's your husband that's gone mad and I'm the one crying."},
		{"5.1 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"5.2 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_FRONT"},
		{"6 Isobella de Vaines?$DIRECT$", L"It's fine. I can scarcely call that thing my husband anymore. I don't know who he has become, because that is not the man I married."},
		{"6.1 $ANIMATEOBJECT$", L"PLAYER1_Olyver Sumner_STAND_FRONT"},
		{"6.2 Olyver Sumner", L"..."},
		{"7 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
		{"8 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
		{"9 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$-1,7,GRASS_-1,7,NOAUDIO$20"},
		{"10 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_LEFT"},
		{"11 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_LEFT"},
		{"12 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$47.5,-1,GRASS_47.5,-1,NOAUDIO$20"},
		{"13 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
		{"14 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
		{"15 Father Michelet?$DIRECT$", L"Excuse me, sir, but..."},
		{"16 $ANIMATEOBJECT$", L"PLAYER1_Olyver Sumner_STAND_BACK"},
		{"17 Father Michelet?$DIRECT$", L"You seem to be very capable of magecraft, even if you say you are just a 'book person'. I am glad you arrived when you did."},
		{"18 Father Michelet$DIRECT$", L"I am Father Michelet, and this is Isobella de Vaines. May we ask who you are?"},
		{"19 Olyver Sumner", L"... oh! Yes, of course. Where are my manners?"},
		{"20 Olyver Sumner", L"I am Olyver Sumner. Graduate student at the University of Vienna."},
		{"21 Olyver Sumner", L"I um... I actually came here to study the unusual weather in this region for a paper I'm writing... but that's not important right now."},
		{"22 Olyver Sumner", L"Clearly you have bigger problems than the whims of a travelling scholar, a murderous knight for example..."},
		{"23 Father Michelet$DIRECT$", L"I am afraid William is only one of many problems we are facing."},
		{"24 Father Michelet$DIRECT$", L"Bénouville cowers in the shrouds of madness. Our townspeople indulge in bizarre, perpetual violence. It's growing worse every day."},
		{"25 Father Michelet$DIRECT$", L"If you would prefer to leave while you can, we will not judge you."},
		{"25.1 Olyver Sumner", L"Well, no."},
		{"26 Olyver Sumner", L"I'm not leaving."},
		{"27 Olyver Sumner", L"I came to this town because its marvelous weather patterns, and my ability to deduce their motions in time and space, will serve as the foundation of my great thesis, and my voice will ring out in a chorus of learned men across the Western World!"},
		{"28 Olyver Sumner", L"And if studies are to be worth reading about, then they must also be worth fighting for!"},
		{"29 Olyver Sumner", L"Lead on, good sir, and point out whatever evil needs to be rectified by my spellcraft!"},
		{"30 Father Michelet$DIRECT$", L"Wow... your enthusiasm is a balm in these times. We gladly accept your help and pray for your safety."},
		{"31 Father Michelet$DIRECT$", L"The remaining townspeople who are untouched by madness have set up a safe zone in the middle of town. You can rest safely there and we may discuss what we know about the evils we face."},
		{"32 Olyver Sumner", L"Lead the way!"},
		{"69 $STOPDIALOGUE$", L""},
		{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene5"},
} },
		{ "HorsemanCutscene4$Hernando Pizarro", {
		{"1 Isobella de Vaines?$DIRECT$", L"Sir, are you okay?! I'm so sorry about all of this..."},
		{"2 $ANIMATEOBJECT$", L"PLAYER1_Hernando Pizarro_STAND_RIGHT"},
		{"2.1 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_STAND_RIGHT"},
		{"3 Hernando Pizarro", L"I am fine, thank you for your concern. But really it is I who should be asking you. What in God's name has turned your husband into such a madman?"},
		{"4 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_FRONT"},
		{"5 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_FRONT"},
		{"6 Isobella de Vaines?$DIRECT$", L"All of Bénouville would be in your debt if you could answer that."},
		{"6.01 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_STAND_LEFT"},
		{"6.02 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_STAND_LEFT"},
		{"6.1 Isobella de Vaines?$DIRECT$", L"You have to understand, I never betrayed my vows to him... I swear it to every saint in heaven..."},
		{"6.2 Hernando Pizarro", L"There is no need to bring the saints into this. I never imagined an honourable woman such as yourself could have done such a thing. You are Isobella, I assume?"},
		{"6.3 Isobella de Vaines$DIRECT$", L"Yes, Isobella de Vaines. And this is Father Michelet."},
		{"7 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_FRONT"},
		{"8 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_FRONT"},
		{"9 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$-1,7,GRASS_-1,7,NOAUDIO$20"},
		{"10 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_LEFT"},
		{"11 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_LEFT"},
		{"12 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$47.5,-1,GRASS_47.5,-1,NOAUDIO$20"},
		{"13 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_STAND_FRONT"},
		{"14 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_STAND_FRONT"},
		{"16 $ANIMATEOBJECT$", L"PLAYER1_Hernando Pizarro_STAND_BACK"},
		{"17 Hernando Pizarro", L"Ah, a man of the church, I see. My father was a priest. It is always a pleasure to meet a man of faith."},
		{"18 Father Michelet$DIRECT$", L"A pleasure to make your acquaintance, good sir. And you are?"},
		{"19 Hernando Pizarro", L"I am Hernando Pizarro. And on my name, I swear to you I will aid you in any way I can."},
		{"20 Father Michelet$DIRECT$", L"Your pledge humbles me, Ser Pizarro. But I must warn you that the knight you just encountered is but one of many of our troubles."},
		{"21 Hernando Pizarro", L"All the more reason for me to stay. From pirates on the Mediterranean to slavers on the shore of Africa, I have built my career on facing danger head on!"},
		{"22 Father Michelet$DIRECT$", L"Career? Did you travel here to work as a mercenary?"},
		{"23 Hernando Pizarro", L"Mercenary is but one of many hats I have worn, and shall do so again today."},
		{"24 Hernando Pizarro", L"But no, the reason I came to Bénouville is actually... well, I suppose it's not important anymore in light of your problems."},
		{"25 Hernando Pizarro", L"I came here to help a friend of mine. A merchant, to be precise, whose shipment was lost after arriving here."},
		{"26 Hernando Pizarro", L"I almost feel embarassed to mention it given what you have been through."},
		{"27 Isobella de Vaines$DIRECT$", L"Perhaps by helping us, we can help you with your missive."},
		{"28 Isobella de Vaines$DIRECT$", L"Come. The townspeople who remain unaffected by madness have established a safe zone in town. There we can discuss what we've learned so far that might help you."},
		{"32 Olyver Sumner", L"Lead the way!"},
		{"69 $STOPDIALOGUE$", L""},
		{"70 $STARTCUTSCENEDIRECTLY$", L"HorsemanCutscene5"},
} },
		{ "HorsemanCutscene5", {
		{"1 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_RIGHT"},
		{"2 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_RIGHT"},
		{"3 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet$53,-1,GRASS_53,-1,NOAUDIO$20"},
		{"4 $ANIMATEOBJECT$", L"Father Michelet_Father Michelet_WALK_BACK"},
		{"5 $ANIMATEOBJECT$", L"Shadow Father Michelet_Shadow Father Michelet_WALK_BACK"},
		{"6 $LOADOBJECT$", L"CutsceneLoadingScreen_0_0_100_50_CutsceneLoadingScreen_ACTION_1_2.0_0.0_1_CENTRE"}, // x_y_layer_animSpeed_sources_sources_sources_scale_opacity_followplayer
		{"7 $CHANGEANIMATIONSPEED$", L"CutsceneLoadingScreen$80$SINGLE_FADEIN"},
		{"8 $ANIMATEOBJECT$", L"Isobella de Vaines_Isobella de Vaines_WALK_RIGHT"},
		{"9 $ANIMATEOBJECT$", L"Shadow Isobella de Vaines_Shadow Isobella de Vaines_WALK_RIGHT"},
		{"10 $MOVEOBJECTS$", L"Father Michelet_Shadow Father Michelet_Isobella de Vaines_Shadow Isobella de Vaines$-1,4,GRASS_-1,4,NOAUDIO_53,-1,NOAUDIO_53,-1,NOAUDIO$50"},
		{"11 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_WALK_RIGHT"},
		{"12 $ANIMATEOBJECT$", L"Shadow PLAYER1_Shadow PLAYER1_WALK_RIGHT"},
		{"13 $MOVEOBJECTS$", L"PLAYER1_Isobella de Vaines_Shadow Isobella de Vaines_Father Michelet_Shadow Father Michelet$52,-1,GRASS_-1,5,NOAUDIO_-1,5,NOAUDIO_-1,0,NOAUDIO_-1,0,NOAUDIO$50"}, // object_where_soundToPlay
		{"15 $MOVEOBJECTS$", L"PLAYER1_Isobella de Vaines_Shadow Isobella de Vaines$-1,5,GRASS_-1,0,NOAUDIO_-1,0,NOAUDIO$50"}, // object_where_soundToPlay
		{"16 $MOVEOBJECTS$", L"PLAYER1$-1,0,GRASS$50"},
		{"17 $ANIMATEOBJECT$", L"PLAYER1_PLAYER1_WALK_BACK"},
		{"50 $WAIT$", L"wait_400"},
		}},
		{ "Grave1", {
		{"1 PLAYER", L"Here lies Girard Olon, born September 28th 1398, died May 20th 1450. A victim of madness, killed by a cart after he ran in front of it.",}
}},
		{ "Grave2", {
		{"1 PLAYER", L"Here lies Henry Pigalle, born June 1st 1432, died May 21st 1450. A victim of madness, he threw himself from the town walls.",}
} },
		{ "Grave3", {
		{"1 PLAYER", L"Here lies Denisette Machecol, born May 18th 1434, died May 19th 1450. Died from drinking well-water poisoned by victims of madness.",}
} },
		{ "Grave4", {
		{"1 PLAYER", L"Here lies Marion Le Mol, born August 5th 1422, died May 28th 1450. Died after being set on fire by one afflicted by madness.",}
} },
		{ "Grave5", {
		{"1 PLAYER", L"Here lies Father Dubois, born September 28th 1391, died May 29th 1450. Killed by an angry mob.",}
} },
		{ "Cat",{
				{"0 $PLAYSFX$", L"CAT_0_0"},
				{"1 Angela Fleuret", L"My my, aren't you a sweet little angel! I see God saw fit to send you to this Earth to be just as cute as you are!"},
				{"1 Tianshun Song", L"If anything bad happens to this cat, I'll kill everyone in this damn town."},
				{"1 Olyver Sumner", L"Oh hello, little kitty! You know, you remind me of my cat at home back in England."},
				{"1 Hernando Pizarro", L"Who's a good boy? You are!"},
				{"1 Gihat al-Din Jaqmaq", L"I shouldn't be wasting my time petting this cat, but just this once... while no one's looking..."},
	}},
		{ "Dog",{
			{"0 $PLAYSFX$", L"DOG_0_0"},
			{"1 Angela Fleuret", L"I trust you'll watch over these people as the make their way to the kingdom of Heaven, right, little one?"},
			{"1 Tianshun Song", L"Such lovely soft fur!"},
			{"1 Olyver Sumner", L"It would be so nice to take this cute dog for a walk and forget about all this... just for a while."},
			{"1 Hernando Pizarro", L"Who's a good girl? You are!"},
			{"1 Gihat al-Din Jaqmaq", L"Excuse me, I'm looking for a man named... hah, just kidding."},
} },
	{ "GraveDiggerDebug", {
		{"0 Father Charlot$DIRECT$", L"This cutscene is changed because the debug flag was set to 1." },
}},
	{ "GraveDigger", {
		{"0 Father Charlot$DIRECT$", L"Good evening, traveller. Have you come to mourn the dead? Take all the time you need."},
		{"0.1 Father Charlot$DIRECT$", L"Please forgive me for how... haphazard and disorganised this must all look to you. You see, we would normally bury our dead in the graveyard of the church on the Bateau Estate."},
		{"1 Father Charlot$DIRECT$", L"But now it's far too dangerous to expect anyone to go there, what with the enraged ones attacking anyone they can get their hands on. The only safe place to bury them is here, in the communal garden."},
		{"2 Father Charlot$DIRECT$", L"That grave over yonder I dug only yesterday for Father Dubois, our most respected and senior priest. He was murdered by a crazed mob of villagers who accused him of... I almost dare not say it, but... of fathering secret children with the married women of the village."},
		{ "4 Father Charlot$DIRECT$", L"That man was a saint among saints! Such an accusation, such hideous ungodly violence, I have no doubt that something is turning the villagers mad. They would have killed me, too, had it not been for the timely intervention of Oudin L'Escot, who helped trap them inside a room in the Church." },
		{ "5 Father Charlot$DIRECT$", L"But I fear not even intervention from God can save their mortal forms from this wicknedness..." }
	}},
	{ "OldWoman1", {
		{"0 Colette Verderonne$DIRECT$", L"Oh hello, dearie. If you're looking to buy combat equipment, you might want to talk to my sister instead. She sells her wares at the Merchants' Palisade which is right behind you."},
		{"1 Colette Verderonne$DIRECT$", L"Oh, you want to talk to me? Well, aren't you sweet. I'm doing just fine, thank you."},
		{"2 Colette Verderonne$DIRECT$", L"When some of the villagers started turning enraged and attacking people, I sent my son, his wife, and my grandchildren to Mondeville, which is the closest neighbouring town."},
		{"3 Colette Verderonne$DIRECT$", L"I got a letter from them yesterday saying they arrived safely, so whatever happens next, I'll be happy knowing they're safe."},
		{"4 Colette Verderonne$DIRECT$", L"My sister and I are too old and stubborn to make the journey, so we're trying to help everyone who's stayed behind."},
	} },
	{ "TownGuards1", {
		{"0 GuardM1$DIRECT$", L"I feel terrible about what happened to de Vaines."},
		{"1 GuardF1$DIRECT$", L"What happened 'to' him?! I think you mean 'what he did'! He murdered five people!"},
		{"2 GuardM1$DIRECT$", L"Seven. Last I heard he killed the Herlays, you know the ones who just moved to the farm south of the village."},
		{"4 GuardF1$DIRECT$", L"A fact which makes your argument all the more indefensible! That man was once our captain! And then he betrayed everything he stood for!"},
		{"5 GuardM1$DIRECT$", L"I know that now. But up until this morning he was man in whose name I served for ten years!"},
		{"6 GuardM1$DIRECT$", L"Whatever happened to him at the Bateau Estate... clearly drove him to the point of madness beyond humanity. Nothing less could have compelled him to kill all those people."},
		{"7 GuardF1$DIRECT$", L"Unless if it were already his desire to kill innocents in the first place, then I refuse to believe that anything beyond himself could make him do that!"},
		{"10 GuardM1$DIRECT$", L"Believing or not believing isn't a choice anymore. It's just a fact. Our friends and neighbours are becoming enraged and attacking one another. A mob of them killed that priest for God's sake! We're only lucky that Oudin L'Escot was there to stop them from killing anyone else."},
		{"11 GuardF1$DIRECT$", L"Yes, Oudin L'Escot... He's only been in town for a few days, but already he's managed to get the enraged ones trapped inside the Chapel on the Estate."},
		{"12 GuardM1$DIRECT$", L"I fear they won't stay trapped for long..."},
	}},
	{ "BeggarF", {
		{"0 PeasantF1$DIRECT$", L"..."},
		{"1 PeasantF1$DIRECT$", L"You new in town? Take my advice. You should get out while you still can."},
		{"2 PeasantF1$DIRECT$", L"Bénouville isn't safe anymore. There are people going around with a 'look' in their eye."},
		{"3 PeasantF1$DIRECT$", L"They are angry. Not angry like a drunk father who hates his children. Angry like a horse thrashing to escape a burning barn. Like their bones are snapping under the weight of rage that seeps and steams and boils out of them and makes them shout and scream and lash out with fists and knives and swords and sticks and..."},
		{"4 PeasantF1$DIRECT$", L"No... not me... not to me... it won't happen to me... because it already happened..."},
		{"5 PeasantF1$DIRECT$", L"It's what they did to Father Dubois. I saw it myself. They said he was an adulterer. But NONE of that is true. He was a GOOD man. The only man for me in this godforsaken place who ever prayed for me, who ever cared about me. And now he's..." },
		{"6 PeasantF1$DIRECT$", L"Just get out of here before it's too late." },
	} },
	{ "Isobella1", {
		{"0 Isobella de Vaines$DIRECT$", L"Good evening, $POLITETITLE$. Thank you for coming to see me so promptly. I'm afraid I have something to ask of you. A favour - one I suspect cannot be delivered upon easily."},
		{"1 Isobella de Vaines$DIRECT$", L"It's about my husband, William...  though I should say... the thing William has become."},
		{"2 Isobella de Vaines$DIRECT$", L"I have prayed on this question to the point of physical pain, and while it wounds me immensely to say this, I must accept the truth about William."},
		{"3 Isobella de Vaines$DIRECT$", L"William has become fully enraged, and is a threat to everyone in Bénouville."},
		{"4 Isobella de Vaines$DIRECT$", L"He is roaming the farmlands outside the town gate, and will likely try to kill anyone he encounters."},
		{"5 Isobella de Vaines$DIRECT$", L"I beg of you, $POLITETITLE$. End his madness, even if it means ending him. I can no longer hold onto the naive hope that he will return to normal, not while so many innocent lives are at stake."},
		{"6 Isobella de Vaines$DIRECT$", L"So... what say you?"},
		{"7 Angela Fleuret", L"Violence in this instance is not only necessary, but wise, given that innocent lives are at risk. I will finish what I started and let you know when the deed is done. That is my duty here, after all."},
		{"7 Tianshun Song", L"I accept this task - if only to prove to you that I'm not just a little girl, but instead, a necromancer more than capable of vanquishing such a creature. I will return once the job is done, maybe then you'll have some respect for me."},
		{"7 Olyver Sumner", L"... I'll do it. I faced him before, so there's no reason I can't do it again. And this time, I'll be the one ambushing him! Leave this to me!"},
		{"7 Hernando Pizarro", L"I will gladly put an end to the Mad Rider's bloodlust. He has done quite enough damage and deserves to be punished for his crimes. Fear not, my lady. I shall return once he is defeated."},
		{"7 Gihat al-Din Jaqmaq", L"I don't normally do freebies for total strangers. However... if that madman ex-husband of yours were to kill the man I'm looking for that would be... unacceptable. Very well. I will deal with the Mad Rider and return here once the work is done."},
	} },
	{ "Michelet1", {
		{"1 Father Michelet$DIRECT$", L"Need to implement this conversation."},
	} },
		{"DEBUG", {
			{"TestString", L".!?Test String➀é hello I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes."},
}}}} };