#pragma once
#include "framework.h"

map<string, map<string, map<string, wstring>>> strings = {
	{"ENG", {
		{"Skill Tree Names", {
			{"Cleromancy", L"Cleromancy"},
			{"Heliomancy", L"Heliomancy"},
			{"Necromancy", L"Necromancy"},
			{"Sangromancy", L"Sangromancy"},
			{"Meteomancy", L"Meteomancy"},
			{"Electromancy", L"Electromancy"},
			{"1H Weapon Mastery", L"1H Wep Mastery"},
			{"Wayfaring", L"Wayfaring"},
			{"Umbromancy", L"Umbromancy"},
			{"Dual Weapon Mastery", L"D Wep Mastery"},
}},
		{"Skill Names", {
			{"DEFAULT_ATTACK", L"Attack"},
			{"DEFAULT_WAIT", L"Wait"},
			{"Heal Wounds", L"Heal Wounds"},
			{"Heavenstrike", L"Heavenstrike"},
			{"Light of Day", L"Light of Day"},
			{"Exile", L"Exile"},
			{"Strength of Reason", L"Strength of Reason"},
}},
		{"Skill Descriptions", {
			{"DEFAULT_ATTACK", L"Perform a physical attack against target foe that deals②$POWER1$ damage."},
			{"DEFAULT_WAIT", L"Skip this current turn." },
			{"Heal Wounds", L"Heal target ally for②$POWER1$ life." },
			{"Heavenstrike", L"Deal②$POWER1$ holy damage to target foe. If the damage is fatal, all allies are healed for②$POWER2$ life and Heavenstrike takes an additional 4 rounds to recharge." },
			{"Light of Day", L"Deal②$POWER1$ holy damage to all undead or demonic foes." },
			{"Strength of Reason", L"Enchant target ally with Strength of Reason for②$POWER1$ rounds. Their physical attacks deal an extra②$POWER2$ holy damage." },
			{"Exile", L"Destroy target summoned creature. Exile takes an additional②$POWER1$ rounds to recharge." },
}},
		{"Skill Actions", {
			{"Wait", L"$WHO$ is waiting..."},
			{"Default_Started", L"$WHO$ is using a skill..."},
			{"Attack_Started", L"$WHO$ is preparing an attack..."},
			{"Spell_Started", L"$WHO$ is casting a spell..."},
			{"Default_Finished", L"$WHO$ uses $SKILLNAME$!"},
			{"Attack_Finished", L"$WHO$ uses $SKILLNAME$!"},
			{"Spell_Finished", L"$WHO$ casts $SKILLNAME$"},
}},
		{"Item Names", {
					{"Withered Secespita", L"Withered Secespita"},
		}},
		{"Item Descriptions", {
					{"Withered Secespita", L"A secespita is an iron-bladed knife ranging from 8 to 10 inches in length with a rounded ivory handle. It usage dates as far back as the 2nd Century AD,  where ritualists of the pre-Christian Roman Empire, known as Flamens and Flaminicae, would use the blade to kill animals as part of a sacrifice. Such an offering would have been made either to a certain God or Goddess, or as a plea for Rome to be victorious in a particular war, or saved from a particular threat. To complete the ritual, the Secespita would then be used to disembowel the victim.\n\nThis Secespita in particular seems to have been forged to have a thinner blade than usual, giving it a 'withered' look. In spite of this characteristic, as well as being well over a thousand years old, it looks to be uncannily well-preserved, as if an Ancient Roman had walked up to you in the street and dropped it calmly into your open palm before walking away."},
		}},
		{"Attribute Names", {
			{"STRENGTH", L"Strength"},
			{"INTELLIGENCE", L"Intelligence"},
			{"VITALITY", L"Vitality"},
			{"PIETY", L"Piety"},
			{"AGILITY", L"Agility"},
			{"LUCK", L"Luck"},
}},
		{"Stat Names", {
			{"LIFE", L"Life"},
			{"ENERGY", L"Energy"},
			{"ENERGYREGEN", L"Energy Regen"},
			{"SPEED", L"Speed"},
}},
		{"GUI", {
			{"SFXVolume", L"SFX Volume"},
			{"AmbienceVolume", L"Ambience Volume"},
			{"MusicVolume", L"Music Volume"},
			{"MANAGEPARTYBUTTON", L"Manage Party"},
			{"RESUMEEXPLOREBUTTON", L"Resume"},
			{"AUDIOOPTIONS", L"Audio Settings"},
			{"QUITBUTTON", L"Quit"},
			{"CANCELBUTTON", L"Cancel"},
			{"FROMAUDIOTOPAUSEBUTTON", L"Return"},
			{"QUITTEXT", L"Are you sure you want to quit? \n\n (Ritual of the Rose automatically saves your progress for when you return)"},
			{"FROMPARTYTOPAUSE", L"Return"},
			{"PARTYMANAGEHELP", L"Help"},
			{"XPOINTSLEFT", L" points left to spend."},
			{"1POINTLEFT", L" point left to spend."},
			{"PHYSICALPOWER", L"Physical Power:\t②"},
			{"MAGICALPOWER", L"Magical Power:\t②"},
			{"NOTEXT", L""},
			{"equipmentToggleText", L"Show / Hide Equipment Effects"},
			{"FROMPARTYTOREFORM", L"Reform Party"},
			{"PARTYLABEL", L"Party"},
			{"RESERVELABEL", L"Reserves"},
			{"FROMPARTYMANAGEMENTTOSKILLMANAGE", L"Change Skills"},
			{"FROMPARTYMANAGEMENTTOEQUIPMENT", L"Change Equipment"},
			{"SELECTCHARACTER", L"Select Character:"},
			{"SKILLTREESELECTION1", L"Select Skill Tree (Current: $REPLACE$)"},
			{"SKILLTREESELECTION2", L"Select Skill Tree (Current: $REPLACE$)"},
}},
		{"DeadHorse", {
			{"1 Angela Fleuret", L"Hmph. I see the situation in Bénouville has become far worse than the one described in the letter."},
			{"2 Angela Fleuret", L"I must find my way into town... and pray I have not arrived too late to stop this."},
			{"1 Tianshun Song", L"This horse looks like it was healthy, well-fed, and full of life before its violent demise."},
			{"2 Tianshun Song", L"To kill it without using its remains for some purpose is such a waste."},
			{"1 Olyver Sumner", L"Good Lord! What on Earth's happened to that poor horse?!"},
			{"2 Olyver Sumner", L"Th-that's a sword sticking out of it! This was no accident..."},
			{"1 Hernando Pizarro", L"Díos mío, what a waste of a fine, healthy horse."},
			{"2 Hernando Pizarro", L"Stealing a man's horse is one thing, but killing it? How despicable."},
			{"1 Gihat al-Din Jaqmaq", L"Whoever killed this horse had no interest in sparing her any pain. Such an inefficient and barbaric wound would have greatly extended her suffering."},
			{"2 Gihat al-Din Jaqmaq", L"The madman who did this may still be close. I must proceed carefully."},
}},
		{"DeadWoman", {
				{"1 Angela Fleuret", L"This trail of carnage is an insult to the civilised world."},
				{"2 Angela Fleuret", L"Jesus give me the strength to extinguish this evil."},
				{"1 Tianshun Song", L"Another life destroyed with no rhyme or reason. How odd. Even the most barbaric Mongol invader kills with some goal in mind. To conquer a town, scare the weak peasants, or even just for the pleasure of killing."},
				{"2 Tianshun Song", L"But all this senseless, emotioness death feels so foreign to me. Killing with no hope or goal in mind. I need to find out more."},
				{"1 Olyver Sumner", L"Oh my God! That woman's been absolutely brutalised! What in God's name is happening in Bénouville?!"},
				{"2 Olyver Sumner", L"Oh I can't bear to look, I think I'm going to be sick!"},
				{"1 Hernando Pizarro", L"Looking at all this fills me with so much anger. Soldiers fighting in war is one thing, but I cannot abide the slaying of this innocent, defenceless woman."},
				{"2 Hernando Pizarro", L"Pity the soul of the man who did this without shame or remorse."},
				{"1 Gihat al-Din Jaqmaq", L"A poor, defenceless peasant woman. No weapon, no training, no hope of surviving whatever did this to you. If I had known you, I would have taught you how to wield a knife, at least."},
				{"2 Gihat al-Din Jaqmaq", L"... what am I saying? I don't have time to pity the dead. I need to keep moving."},
	}},
		{"DeadMan", {
				{"1 Angela Fleuret", L"These wounds are fresh, and by the looks of it, inflicted with a bladed weapon wielded with a great deal of strength."},
				{"2 Angela Fleuret", L"Whoever did this can't have gotten far. I will find him and put an end to him."},
				{"1 Tianshun Song", L"This man's life force was cut short very recently, I can feel it."},
				{"2 Tianshun Song", L"Perhaps if I'd gotten here quicker I could have seen who did it."},
				{"1 Olyver Sumner", L"Even if I turned around now, I could never hope the reach the nearest town before sunset. Then I would be alone in the dark with whatever freak of nature did these terrible things. Look at me... I'm so scared, I'm shaking."},
				{"2 Olyver Sumner", L"N-no! I won't be afraid! I will fight if I have to!"},
				{"1 Hernando Pizarro", L"No survivors so far. Díos... is the rest of the town like this?!"},
				{"2 Hernando Pizarro", L"No matter. If I find the man responsible for this, I will bring swift justice to him, or my name isn't Hernando Pizarro!"},
				{"1 Gihat al-Din Jaqmaq", L"These wounds are fresh. This can't have happened that long ago."},
				{"2 Gihat al-Din Jaqmaq", L"I must keep my wits about me in this town. As long as I maintain my composure, this carnage won't become a distraction."},
	}},
		{"Fireplace1", {
				{"1 Angela Fleuret", L"My journey here from the Vatican was one of speed rather than comfort. 'Tis a welcome change of pace to finally be somewhere warm and dry with a simple fireplace and the smell of cooking."},
				{"1 Tianshun Song", L"I felt the pull of this town's negative energy all the way from Paris and I haven't rested since. Perhaps I could close my eyes just for a moment..."},
				{"1 Olyver Sumner", L"What a lovely hearth. If I wasn't haunted by the idea of a psycho killer hiding upstairs I'd probably lie down and rest my eyes."},
				{"1 Hernando Pizarro", L"Ah... to lay by such a fire with a glass of wine, a good friend and passionate conversation... maybe another time."},
				{"1 Gihat al-Din Jaqmaq", L"I shouldn't be wasting any more time standing in this dead peasant's house!"},
	}},
		{"DEBUG", {
			{"TestString", L".!?Test String➀é hello I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes. I am a long string used to test the cropping of text boxes."},
}}}} };